--
-- PostgreSQL database dump
--



-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: brincadeiras; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.brincadeiras (
    id character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(500),
    rules text,
    type character varying(20) DEFAULT 'team'::character varying,
    duration integer DEFAULT 30,
    status character varying(20) DEFAULT 'active'::character varying,
    default_points integer DEFAULT 10,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    empresa_id character varying(36),
    game_type character varying(50) DEFAULT 'standard'::character varying,
    checkpoints text,
    evento_id text
);


ALTER TABLE public.brincadeiras OWNER TO postgres;

--
-- Name: caca_tesouro_partidas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caca_tesouro_partidas (
    id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    brincadeira_id character varying(36) NOT NULL,
    status character varying(20) NOT NULL,
    round_number integer NOT NULL,
    target_checkpoint_id character varying(36),
    completed_checkpoint_ids text,
    started_at timestamp with time zone NOT NULL,
    round_started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    starting_team_id character varying(36),
    turn_team_id character varying(36),
    turn_available_at timestamp with time zone
);


ALTER TABLE public.caca_tesouro_partidas OWNER TO postgres;

--
-- Name: caca_tesouro_scans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caca_tesouro_scans (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    brincadeira_id character varying(36) NOT NULL,
    round_number integer NOT NULL,
    checkpoint_id character varying(36) NOT NULL,
    crianca_id character varying(36) NOT NULL,
    time_id character varying(36) NOT NULL,
    uid character varying(100) NOT NULL,
    scanned_at timestamp with time zone NOT NULL
);


ALTER TABLE public.caca_tesouro_scans OWNER TO postgres;

--
-- Name: caca_tesouro_tempos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caca_tesouro_tempos (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    time_id character varying(36) NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    elapsed_ms bigint
);


ALTER TABLE public.caca_tesouro_tempos OWNER TO postgres;

--
-- Name: checkpoint_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.checkpoint_tags (
    id integer NOT NULL,
    checkpoint_id character varying(36) NOT NULL,
    tag_uid character varying(50) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.checkpoint_tags OWNER TO postgres;

--
-- Name: checkpoint_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.checkpoint_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.checkpoint_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: checkpoints; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.checkpoints (
    id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(20) DEFAULT 'NFC'::character varying,
    ip character varying(15),
    zone character varying(100),
    led_color character varying(20) DEFAULT '#00FF00'::character varying,
    points integer DEFAULT 10,
    status character varying(20) DEFAULT 'offline'::character varying,
    territory_owner_time_id character varying(36),
    territory_locked_until timestamp with time zone,
    territory_cooldown_until timestamp with time zone,
    last_conquered_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    empresa_id character varying(36),
    authorized_tags text,
    last_seen timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    location character varying(100),
    checkpoint_purpose character varying(20) DEFAULT 'game'::character varying,
    map_x integer,
    map_y integer,
    territory_owner_crianca_id character varying(36)
);


ALTER TABLE public.checkpoints OWNER TO postgres;

--
-- Name: clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes (
    id character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    city character varying(100),
    state character varying(2),
    email character varying(100) NOT NULL,
    phone character varying(20),
    plano character varying(20) DEFAULT 'starter'::character varying,
    status character varying(20) DEFAULT 'active'::character varying,
    events_done integer DEFAULT 0,
    last_access timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    empresa_id character varying(36),
    address character varying(255),
    backup_frequency character varying(20) DEFAULT 'daily'::character varying
);


ALTER TABLE public.clientes OWNER TO postgres;

--
-- Name: conquistas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conquistas (
    id character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(500),
    icon character varying(50),
    color character varying(20),
    required_type character varying(50),
    required_value integer,
    points_bonus integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.conquistas OWNER TO postgres;

--
-- Name: crianca_conquistas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.crianca_conquistas (
    crianca_id character varying(36) NOT NULL,
    conquista_id character varying(36) NOT NULL,
    unlocked_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.crianca_conquistas OWNER TO postgres;

--
-- Name: criancas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.criancas (
    id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    time_id character varying(36),
    name character varying(100) NOT NULL,
    nickname character varying(100),
    age integer,
    avatar character varying(64) DEFAULT '??'::character varying,
    bracelet_code character varying(50),
    scores integer DEFAULT 0,
    status character varying(20) DEFAULT 'active'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    empresa_id character varying(36),
    qr_code character varying
);


ALTER TABLE public.criancas OWNER TO postgres;

--
-- Name: empresa_event_control; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empresa_event_control (
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36),
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.empresa_event_control OWNER TO postgres;

--
-- Name: empresas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empresas (
    id character varying(36) NOT NULL,
    nome character varying(255) NOT NULL,
    cidade character varying(100),
    estado character varying(2),
    telefone character varying(20),
    plano character varying(50) DEFAULT 'starter'::character varying,
    status character varying(50) DEFAULT 'active'::character varying,
    data_criacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    latitude double precision,
    longitude double precision,
    cnpj character varying(14),
    floor_plan_data text,
    floor_plan_name character varying(255),
    floor_plan_type character varying(100),
    zones_data text
);


ALTER TABLE public.empresas OWNER TO postgres;

--
-- Name: event_game_state; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.event_game_state (
    evento_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    mode character varying(20) DEFAULT 'idle'::character varying NOT NULL,
    game_type character varying(50) DEFAULT 'none'::character varying NOT NULL,
    game_id character varying(36),
    game_name character varying(255),
    started_at timestamp with time zone,
    stopped_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.event_game_state OWNER TO postgres;

--
-- Name: evento_brincadeiras; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evento_brincadeiras (
    evento_id character varying(36) NOT NULL,
    brincadeira_id character varying(36) NOT NULL,
    ordem integer DEFAULT 0,
    points_multiplier integer DEFAULT 1,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.evento_brincadeiras OWNER TO postgres;

--
-- Name: eventos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eventos (
    id character varying(36) NOT NULL,
    cliente_id character varying(36),
    name character varying(100) NOT NULL,
    description character varying(500),
    date date NOT NULL,
    "time" time without time zone,
    duration integer DEFAULT 120,
    status character varying(20) DEFAULT 'scheduled'::character varying,
    enable_display integer DEFAULT 1,
    enable_location integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    empresa_id character varying(36),
    active_game_type character varying(50) DEFAULT 'none'::character varying,
    active_brincadeira_id character varying(36),
    floor_plan_data text,
    floor_plan_name character varying(255),
    floor_plan_type character varying(100),
    zones_data text,
    responsible_name character varying(150),
    started_at timestamp with time zone,
    ended_at timestamp with time zone,
    auto_start integer DEFAULT 0,
    auto_end integer DEFAULT 0
);


ALTER TABLE public.eventos OWNER TO postgres;

--
-- Name: family_child_links; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.family_child_links (
    id character varying(36) NOT NULL,
    login_id character varying(36) NOT NULL,
    crianca_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    relationship character varying(50) DEFAULT 'responsável'::character varying NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    approved_by character varying(36),
    approved_at timestamp with time zone,
    rejected_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.family_child_links OWNER TO postgres;

--
-- Name: family_invites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.family_invites (
    id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    crianca_id character varying(36),
    email character varying(255),
    token_hash character varying(128) NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_by character varying(36),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.family_invites OWNER TO postgres;

--
-- Name: family_linking_codes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.family_linking_codes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    crianca_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    qr_code_value character varying(50) NOT NULL,
    tracking_url character varying(500) NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp without time zone NOT NULL,
    used_at timestamp without time zone,
    used_by_login_id character varying(36)
);


ALTER TABLE public.family_linking_codes OWNER TO postgres;

--
-- Name: game_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.game_sessions (
    id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    brincadeira_id character varying(36) NOT NULL,
    game_type character varying(50) NOT NULL,
    mode character varying(20),
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finished_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.game_sessions OWNER TO postgres;

--
-- Name: game_winner_bonuses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.game_winner_bonuses (
    id character varying(36) NOT NULL,
    empresa_id character varying(36),
    evento_id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    game_type character varying(50) NOT NULL,
    time_id character varying(36) NOT NULL,
    points_per_member integer DEFAULT 0 NOT NULL,
    members_awarded integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.game_winner_bonuses OWNER TO postgres;

--
-- Name: leituras; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leituras (
    id character varying(36) NOT NULL,
    checkpoint_id character varying(36) NOT NULL,
    crianca_id character varying(36),
    uid character varying(50) NOT NULL,
    brincadeira_id text,
    authorized integer DEFAULT 0,
    points_awarded integer DEFAULT 0,
    signal_strength integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    empresa_id character varying(36),
    session_id character varying(36)
);


ALTER TABLE public.leituras OWNER TO postgres;

--
-- Name: logins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.logins (
    id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    status character varying(50) DEFAULT 'active'::character varying,
    ultimo_acesso timestamp with time zone,
    data_criacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    role character varying(50) DEFAULT 'admin'::character varying,
    family_name character varying(255)
);


ALTER TABLE public.logins OWNER TO postgres;

--
-- Name: logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.logs (
    id integer NOT NULL,
    tipo character varying(20) NOT NULL,
    cliente_id character varying(36),
    evento_id character varying(36),
    message character varying(500) NOT NULL,
    details text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    empresa_id character varying(36)
);


ALTER TABLE public.logs OWNER TO postgres;

--
-- Name: logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensagens_display; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mensagens_display (
    id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    text character varying(500) NOT NULL,
    type character varying(20) DEFAULT 'custom'::character varying,
    sender character varying(100),
    sent_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.mensagens_display OWNER TO postgres;

--
-- Name: monster_hunt_partidas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.monster_hunt_partidas (
    id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    brincadeira_id character varying(36),
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    hp integer DEFAULT 100 NOT NULL,
    max_hp integer DEFAULT 100 NOT NULL,
    normal_damage integer DEFAULT 10 NOT NULL,
    special_checkpoint_damage integer DEFAULT 30 NOT NULL,
    special_attack_damage integer DEFAULT 50 NOT NULL,
    special_checkpoint_id character varying(36),
    winner_time_id character varying(36),
    version integer DEFAULT 0 NOT NULL,
    started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finished_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.monster_hunt_partidas OWNER TO postgres;

--
-- Name: monster_hunt_scans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.monster_hunt_scans (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    brincadeira_id character varying(36),
    checkpoint_id character varying(36) NOT NULL,
    crianca_id character varying(36) NOT NULL,
    time_id character varying(36),
    uid character varying(255),
    leitura_id character varying(36),
    attack_type character varying(30) NOT NULL,
    damage integer DEFAULT 0 NOT NULL,
    monster_hp_after integer NOT NULL,
    monster_defeated boolean DEFAULT false NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    scanned_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.monster_hunt_scans OWNER TO postgres;

--
-- Name: monster_hunt_team_states; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.monster_hunt_team_states (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    time_id character varying(36) NOT NULL,
    hp integer DEFAULT 500 NOT NULL,
    max_hp integer DEFAULT 500 NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    defeated_at timestamp with time zone,
    victory_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.monster_hunt_team_states OWNER TO postgres;

--
-- Name: pontuacoes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pontuacoes (
    id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    crianca_id character varying(36) NOT NULL,
    brincadeira_id text,
    checkpoint_id character varying(36) NOT NULL,
    points integer NOT NULL,
    leitura_id character varying(36),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    empresa_id character varying(36)
);


ALTER TABLE public.pontuacoes OWNER TO postgres;

--
-- Name: pulseiras; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pulseiras (
    code character varying(50) NOT NULL,
    status character varying(20) DEFAULT 'disponivel'::character varying,
    crianca_id character varying(36),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    empresa_id character varying(36)
);


ALTER TABLE public.pulseiras OWNER TO postgres;

--
-- Name: settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.settings (
    id integer NOT NULL,
    setting_key character varying(100) NOT NULL,
    setting_value text,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    empresa_id text
);


ALTER TABLE public.settings OWNER TO postgres;

--
-- Name: settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: staff; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.staff (
    id character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    role character varying(50) NOT NULL,
    login character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    status character varying(20) DEFAULT 'offline'::character varying,
    last_access timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.staff OWNER TO postgres;

--
-- Name: support_tickets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.support_tickets (
    id character varying(36) NOT NULL,
    empresa_id character varying(36),
    client character varying(255) NOT NULL,
    subject character varying(255) NOT NULL,
    status character varying(20) DEFAULT 'aberto'::character varying NOT NULL,
    priority character varying(20) DEFAULT 'media'::character varying NOT NULL,
    description text,
    assignee character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.support_tickets OWNER TO postgres;

--
-- Name: times; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.times (
    id character varying(36) NOT NULL,
    evento_id character varying(36),
    name character varying(50) NOT NULL,
    color character varying(20) NOT NULL,
    points integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    empresa_id character varying(36)
);


ALTER TABLE public.times OWNER TO postgres;

--
-- Name: zonas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zonas (
    id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    color character varying(20) NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.zonas OWNER TO postgres;

--
-- Name: zonas_equipes_partidas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zonas_equipes_partidas (
    id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    brincadeira_id character varying(36),
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finished_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.zonas_equipes_partidas OWNER TO postgres;

--
-- Name: zonas_equipes_scans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zonas_equipes_scans (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    brincadeira_id character varying(36),
    checkpoint_id character varying(36) NOT NULL,
    crianca_id character varying(36) NOT NULL,
    time_id character varying(36),
    uid character varying(255),
    leitura_id character varying(36),
    version integer DEFAULT 0 NOT NULL,
    scanned_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.zonas_equipes_scans OWNER TO postgres;

--
-- Name: zonas_equipes_teams_states; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zonas_equipes_teams_states (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    time_id character varying(36) NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    defeated_at timestamp with time zone,
    victory_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.zonas_equipes_teams_states OWNER TO postgres;

--
-- Name: zone_conquest_checkpoint_states; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zone_conquest_checkpoint_states (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    checkpoint_id character varying(36) NOT NULL,
    current_owner_id character varying(36),
    owner_type character varying(20) DEFAULT 'team'::character varying NOT NULL,
    protected_until timestamp with time zone,
    last_conquered_at timestamp with time zone,
    conquest_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.zone_conquest_checkpoint_states OWNER TO postgres;

--
-- Name: zone_conquest_individual_checkpoint_protection; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zone_conquest_individual_checkpoint_protection (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    checkpoint_id character varying(36) NOT NULL,
    crianca_id character varying(36) NOT NULL,
    protection_until timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.zone_conquest_individual_checkpoint_protection OWNER TO postgres;

--
-- Name: zone_conquest_individual_participant_states; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zone_conquest_individual_participant_states (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    crianca_id character varying(36) NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    checkpoints_read integer DEFAULT 0 NOT NULL,
    total_points numeric(10,2) DEFAULT 0 NOT NULL,
    ranking integer,
    version integer DEFAULT 0 NOT NULL,
    started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finished_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    color character varying(50)
);


ALTER TABLE public.zone_conquest_individual_participant_states OWNER TO postgres;

--
-- Name: zone_conquest_individual_partidas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zone_conquest_individual_partidas (
    id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    brincadeira_id character varying(36) NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finished_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.zone_conquest_individual_partidas OWNER TO postgres;

--
-- Name: zone_conquest_individual_scans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zone_conquest_individual_scans (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    brincadeira_id character varying(36) NOT NULL,
    checkpoint_id character varying(36) NOT NULL,
    crianca_id character varying(36) NOT NULL,
    uid character varying(255),
    leitura_id character varying(36),
    points_awarded numeric(10,2) DEFAULT 0 NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    scanned_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.zone_conquest_individual_scans OWNER TO postgres;

--
-- Name: zone_conquest_team_partidas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zone_conquest_team_partidas (
    id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    brincadeira_id character varying(36) NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    round_number integer DEFAULT 1 NOT NULL,
    current_team_id character varying(36),
    started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finished_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.zone_conquest_team_partidas OWNER TO postgres;

--
-- Name: zone_conquest_team_scans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zone_conquest_team_scans (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    brincadeira_id character varying(36) NOT NULL,
    round_number integer NOT NULL,
    checkpoint_id character varying(36) NOT NULL,
    crianca_id character varying(36) NOT NULL,
    time_id character varying(36) NOT NULL,
    uid character varying(255),
    leitura_id character varying(36),
    points_awarded numeric(10,2) DEFAULT 0 NOT NULL,
    scanned_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.zone_conquest_team_scans OWNER TO postgres;

--
-- Name: zone_conquest_team_tempos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zone_conquest_team_tempos (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    time_id character varying(36) NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    zones_dominated integer DEFAULT 0 NOT NULL,
    checkpoints_read integer DEFAULT 0 NOT NULL,
    total_points numeric(10,2) DEFAULT 0 NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    elapsed_ms integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.zone_conquest_team_tempos OWNER TO postgres;

--
-- Name: zone_conquest_zone_states; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zone_conquest_zone_states (
    id character varying(36) NOT NULL,
    partida_id character varying(36) NOT NULL,
    empresa_id character varying(36) NOT NULL,
    evento_id character varying(36) NOT NULL,
    zone_id character varying(36) NOT NULL,
    current_owner_id character varying(36),
    owner_type character varying(20) DEFAULT 'team'::character varying NOT NULL,
    is_disputed boolean DEFAULT false NOT NULL,
    checkpoints_count integer DEFAULT 0 NOT NULL,
    checkpoints_owned integer DEFAULT 0 NOT NULL,
    last_updated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.zone_conquest_zone_states OWNER TO postgres;

--
-- Name: brincadeiras PK__brincade__3213E83FA8E61AF2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.brincadeiras
    ADD CONSTRAINT "PK__brincade__3213E83FA8E61AF2" PRIMARY KEY (id);


--
-- Name: caca_tesouro_scans PK__caca_tes__3213E83F600198BE; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caca_tesouro_scans
    ADD CONSTRAINT "PK__caca_tes__3213E83F600198BE" PRIMARY KEY (id);


--
-- Name: caca_tesouro_partidas PK__caca_tes__3213E83F8450C49A; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caca_tesouro_partidas
    ADD CONSTRAINT "PK__caca_tes__3213E83F8450C49A" PRIMARY KEY (id);


--
-- Name: caca_tesouro_tempos PK__caca_tes__3213E83F976260F2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caca_tesouro_tempos
    ADD CONSTRAINT "PK__caca_tes__3213E83F976260F2" PRIMARY KEY (id);


--
-- Name: checkpoints PK__checkpoi__3213E83FB6D1708F; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checkpoints
    ADD CONSTRAINT "PK__checkpoi__3213E83FB6D1708F" PRIMARY KEY (id);


--
-- Name: checkpoint_tags PK__checkpoi__3213E83FB8065A13; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checkpoint_tags
    ADD CONSTRAINT "PK__checkpoi__3213E83FB8065A13" PRIMARY KEY (id);


--
-- Name: clientes PK__clientes__3213E83F6BF1E412; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT "PK__clientes__3213E83F6BF1E412" PRIMARY KEY (id);


--
-- Name: conquistas PK__conquist__3213E83F4F0D26FA; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conquistas
    ADD CONSTRAINT "PK__conquist__3213E83F4F0D26FA" PRIMARY KEY (id);


--
-- Name: crianca_conquistas PK__crianca___213C2CFF26481BB9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.crianca_conquistas
    ADD CONSTRAINT "PK__crianca___213C2CFF26481BB9" PRIMARY KEY (crianca_id, conquista_id);


--
-- Name: criancas PK__criancas__3213E83F76B74F48; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.criancas
    ADD CONSTRAINT "PK__criancas__3213E83F76B74F48" PRIMARY KEY (id);


--
-- Name: empresas PK__empresas__3213E83FC96C8FA1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT "PK__empresas__3213E83FC96C8FA1" PRIMARY KEY (id);


--
-- Name: evento_brincadeiras PK__evento_b__C4A104BA0DD4DCE7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evento_brincadeiras
    ADD CONSTRAINT "PK__evento_b__C4A104BA0DD4DCE7" PRIMARY KEY (evento_id, brincadeira_id);


--
-- Name: eventos PK__eventos__3213E83FBD04E5E4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos
    ADD CONSTRAINT "PK__eventos__3213E83FBD04E5E4" PRIMARY KEY (id);


--
-- Name: leituras PK__leituras__3213E83F5D36D3D4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leituras
    ADD CONSTRAINT "PK__leituras__3213E83F5D36D3D4" PRIMARY KEY (id);


--
-- Name: logins PK__logins__3213E83F57818161; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.logins
    ADD CONSTRAINT "PK__logins__3213E83F57818161" PRIMARY KEY (id);


--
-- Name: logs PK__logs__3213E83FFD30ACAA; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT "PK__logs__3213E83FFD30ACAA" PRIMARY KEY (id);


--
-- Name: mensagens_display PK__mensagen__3213E83F95810D6B; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensagens_display
    ADD CONSTRAINT "PK__mensagen__3213E83F95810D6B" PRIMARY KEY (id);


--
-- Name: pontuacoes PK__pontuaco__3213E83FE7FD06CA; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pontuacoes
    ADD CONSTRAINT "PK__pontuaco__3213E83FE7FD06CA" PRIMARY KEY (id);


--
-- Name: pulseiras PK__pulseira__357D4CF8CB99523E; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pulseiras
    ADD CONSTRAINT "PK__pulseira__357D4CF8CB99523E" PRIMARY KEY (code);


--
-- Name: settings PK__settings__3213E83F4D79CD35; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT "PK__settings__3213E83F4D79CD35" PRIMARY KEY (id);


--
-- Name: staff PK__staff__3213E83F80857AE0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT "PK__staff__3213E83F80857AE0" PRIMARY KEY (id);


--
-- Name: times PK__times__3213E83FE6C742EE; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.times
    ADD CONSTRAINT "PK__times__3213E83FE6C742EE" PRIMARY KEY (id);


--
-- Name: zonas PK__zonas__3213E83F534C9F84; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zonas
    ADD CONSTRAINT "PK__zonas__3213E83F534C9F84" PRIMARY KEY (id);


--
-- Name: logins UQ__logins__AB6E61641C935B6A; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.logins
    ADD CONSTRAINT "UQ__logins__AB6E61641C935B6A" UNIQUE (email);


--
-- Name: staff UQ__staff__7838F27224FF163E; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT "UQ__staff__7838F27224FF163E" UNIQUE (login);


--
-- Name: caca_tesouro_scans UQ_caca_tesouro_scan_crianca; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caca_tesouro_scans
    ADD CONSTRAINT "UQ_caca_tesouro_scan_crianca" UNIQUE (partida_id, round_number, crianca_id);


--
-- Name: caca_tesouro_tempos UQ_caca_tesouro_tempo_equipe; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caca_tesouro_tempos
    ADD CONSTRAINT "UQ_caca_tesouro_tempo_equipe" UNIQUE (partida_id, time_id);


--
-- Name: checkpoint_tags UQ_checkpoint_tag; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checkpoint_tags
    ADD CONSTRAINT "UQ_checkpoint_tag" UNIQUE (checkpoint_id, tag_uid);


--
-- Name: criancas criancas_qr_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.criancas
    ADD CONSTRAINT criancas_qr_code_key UNIQUE (qr_code);


--
-- Name: empresa_event_control empresa_event_control_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa_event_control
    ADD CONSTRAINT empresa_event_control_pkey PRIMARY KEY (empresa_id);


--
-- Name: event_game_state event_game_state_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_game_state
    ADD CONSTRAINT event_game_state_pkey PRIMARY KEY (evento_id);


--
-- Name: family_child_links family_child_links_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.family_child_links
    ADD CONSTRAINT family_child_links_pkey PRIMARY KEY (id);


--
-- Name: family_invites family_invites_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.family_invites
    ADD CONSTRAINT family_invites_pkey PRIMARY KEY (id);


--
-- Name: family_linking_codes family_linking_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.family_linking_codes
    ADD CONSTRAINT family_linking_codes_pkey PRIMARY KEY (id);


--
-- Name: family_linking_codes family_linking_codes_qr_code_value_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.family_linking_codes
    ADD CONSTRAINT family_linking_codes_qr_code_value_key UNIQUE (qr_code_value);


--
-- Name: game_sessions game_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_sessions
    ADD CONSTRAINT game_sessions_pkey PRIMARY KEY (id);


--
-- Name: game_winner_bonuses game_winner_bonuses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_winner_bonuses
    ADD CONSTRAINT game_winner_bonuses_pkey PRIMARY KEY (id);


--
-- Name: monster_hunt_partidas monster_hunt_partidas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monster_hunt_partidas
    ADD CONSTRAINT monster_hunt_partidas_pkey PRIMARY KEY (id);


--
-- Name: monster_hunt_scans monster_hunt_scans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monster_hunt_scans
    ADD CONSTRAINT monster_hunt_scans_pkey PRIMARY KEY (id);


--
-- Name: monster_hunt_team_states monster_hunt_team_states_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monster_hunt_team_states
    ADD CONSTRAINT monster_hunt_team_states_pkey PRIMARY KEY (id);


--
-- Name: support_tickets support_tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.support_tickets
    ADD CONSTRAINT support_tickets_pkey PRIMARY KEY (id);


--
-- Name: zonas_equipes_partidas zonas_equipes_partidas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zonas_equipes_partidas
    ADD CONSTRAINT zonas_equipes_partidas_pkey PRIMARY KEY (id);


--
-- Name: zonas_equipes_scans zonas_equipes_scans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zonas_equipes_scans
    ADD CONSTRAINT zonas_equipes_scans_pkey PRIMARY KEY (id);


--
-- Name: zonas_equipes_teams_states zonas_equipes_teams_states_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zonas_equipes_teams_states
    ADD CONSTRAINT zonas_equipes_teams_states_pkey PRIMARY KEY (id);


--
-- Name: zone_conquest_checkpoint_states zone_conquest_checkpoint_states_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zone_conquest_checkpoint_states
    ADD CONSTRAINT zone_conquest_checkpoint_states_pkey PRIMARY KEY (id);


--
-- Name: zone_conquest_individual_checkpoint_protection zone_conquest_individual_checkpoint_protection_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zone_conquest_individual_checkpoint_protection
    ADD CONSTRAINT zone_conquest_individual_checkpoint_protection_pkey PRIMARY KEY (id);


--
-- Name: zone_conquest_individual_participant_states zone_conquest_individual_participant_states_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zone_conquest_individual_participant_states
    ADD CONSTRAINT zone_conquest_individual_participant_states_pkey PRIMARY KEY (id);


--
-- Name: zone_conquest_individual_partidas zone_conquest_individual_partidas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zone_conquest_individual_partidas
    ADD CONSTRAINT zone_conquest_individual_partidas_pkey PRIMARY KEY (id);


--
-- Name: zone_conquest_individual_scans zone_conquest_individual_scans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zone_conquest_individual_scans
    ADD CONSTRAINT zone_conquest_individual_scans_pkey PRIMARY KEY (id);


--
-- Name: zone_conquest_team_partidas zone_conquest_team_partidas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zone_conquest_team_partidas
    ADD CONSTRAINT zone_conquest_team_partidas_pkey PRIMARY KEY (id);


--
-- Name: zone_conquest_team_scans zone_conquest_team_scans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zone_conquest_team_scans
    ADD CONSTRAINT zone_conquest_team_scans_pkey PRIMARY KEY (id);


--
-- Name: zone_conquest_team_tempos zone_conquest_team_tempos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zone_conquest_team_tempos
    ADD CONSTRAINT zone_conquest_team_tempos_pkey PRIMARY KEY (id);


--
-- Name: zone_conquest_zone_states zone_conquest_zone_states_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zone_conquest_zone_states
    ADD CONSTRAINT zone_conquest_zone_states_pkey PRIMARY KEY (id);


--
-- Name: idx_event_game_state_empresa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_event_game_state_empresa ON public.event_game_state USING btree (empresa_id);


--
-- Name: idx_flc_crianca; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_flc_crianca ON public.family_linking_codes USING btree (crianca_id);


--
-- Name: idx_flc_empresa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_flc_empresa ON public.family_linking_codes USING btree (empresa_id);


--
-- Name: idx_flc_qr_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_flc_qr_code ON public.family_linking_codes USING btree (qr_code_value);


--
-- Name: idx_flc_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_flc_status ON public.family_linking_codes USING btree (status);


--
-- Name: idx_game_sessions_brincadeira; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_game_sessions_brincadeira ON public.game_sessions USING btree (brincadeira_id);


--
-- Name: idx_game_sessions_evento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_game_sessions_evento ON public.game_sessions USING btree (evento_id);


--
-- Name: idx_game_sessions_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_game_sessions_status ON public.game_sessions USING btree (status);


--
-- Name: idx_game_winner_bonuses_evento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_game_winner_bonuses_evento ON public.game_winner_bonuses USING btree (evento_id);


--
-- Name: idx_leituras_session_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_leituras_session_id ON public.leituras USING btree (session_id);


--
-- Name: idx_monster_hunt_partidas_evento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monster_hunt_partidas_evento ON public.monster_hunt_partidas USING btree (empresa_id, evento_id, status);


--
-- Name: idx_monster_hunt_scans_checkpoint; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monster_hunt_scans_checkpoint ON public.monster_hunt_scans USING btree (partida_id, checkpoint_id, scanned_at);


--
-- Name: idx_monster_hunt_scans_evento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monster_hunt_scans_evento ON public.monster_hunt_scans USING btree (empresa_id, evento_id, partida_id);


--
-- Name: idx_monster_hunt_team_states_evento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monster_hunt_team_states_evento ON public.monster_hunt_team_states USING btree (empresa_id, evento_id, partida_id);


--
-- Name: idx_zcip_evento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zcip_evento ON public.zone_conquest_individual_partidas USING btree (evento_id);


--
-- Name: idx_zcip_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zcip_status ON public.zone_conquest_individual_partidas USING btree (status);


--
-- Name: idx_zcips_crianca; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zcips_crianca ON public.zone_conquest_individual_participant_states USING btree (crianca_id);


--
-- Name: idx_zcips_partida; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zcips_partida ON public.zone_conquest_individual_participant_states USING btree (partida_id);


--
-- Name: idx_zcis_crianca; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zcis_crianca ON public.zone_conquest_individual_scans USING btree (crianca_id);


--
-- Name: idx_zcis_leitura; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zcis_leitura ON public.zone_conquest_individual_scans USING btree (leitura_id);


--
-- Name: idx_zcis_partida; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zcis_partida ON public.zone_conquest_individual_scans USING btree (partida_id);


--
-- Name: idx_zonas_equipes_partidas_evento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zonas_equipes_partidas_evento ON public.zonas_equipes_partidas USING btree (empresa_id, evento_id, status);


--
-- Name: idx_zonas_equipes_scans_checkpoint; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zonas_equipes_scans_checkpoint ON public.zonas_equipes_scans USING btree (partida_id, checkpoint_id, scanned_at);


--
-- Name: idx_zonas_equipes_scans_evento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zonas_equipes_scans_evento ON public.zonas_equipes_scans USING btree (empresa_id, evento_id, partida_id);


--
-- Name: idx_zonas_equipes_team_states_evento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zonas_equipes_team_states_evento ON public.zonas_equipes_teams_states USING btree (empresa_id, evento_id, partida_id);


--
-- Name: idx_zone_checkpoint_state_owner; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zone_checkpoint_state_owner ON public.zone_conquest_checkpoint_states USING btree (partida_id, current_owner_id);


--
-- Name: idx_zone_checkpoint_state_partida; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zone_checkpoint_state_partida ON public.zone_conquest_checkpoint_states USING btree (partida_id, checkpoint_id);


--
-- Name: idx_zone_individual_partidas_evento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zone_individual_partidas_evento ON public.zone_conquest_individual_partidas USING btree (evento_id, status);


--
-- Name: idx_zone_individual_protection_checkpoint; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zone_individual_protection_checkpoint ON public.zone_conquest_individual_checkpoint_protection USING btree (checkpoint_id, protection_until);


--
-- Name: idx_zone_individual_scans_partida; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zone_individual_scans_partida ON public.zone_conquest_individual_scans USING btree (partida_id, crianca_id);


--
-- Name: idx_zone_individual_states_partida; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zone_individual_states_partida ON public.zone_conquest_individual_participant_states USING btree (partida_id, crianca_id);


--
-- Name: idx_zone_team_partidas_evento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zone_team_partidas_evento ON public.zone_conquest_team_partidas USING btree (evento_id, status);


--
-- Name: idx_zone_team_scans_partida; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zone_team_scans_partida ON public.zone_conquest_team_scans USING btree (partida_id, round_number);


--
-- Name: idx_zone_team_tempos_partida; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zone_team_tempos_partida ON public.zone_conquest_team_tempos USING btree (partida_id, time_id);


--
-- Name: idx_zone_zone_state_owner; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zone_zone_state_owner ON public.zone_conquest_zone_states USING btree (partida_id, current_owner_id);


--
-- Name: idx_zone_zone_state_partida; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_zone_zone_state_partida ON public.zone_conquest_zone_states USING btree (partida_id, zone_id);


--
-- Name: uq_clientes_empresa_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_clientes_empresa_id ON public.clientes USING btree (empresa_id) WHERE (empresa_id IS NOT NULL);


--
-- Name: uq_family_child_link; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_family_child_link ON public.family_child_links USING btree (login_id, crianca_id);


--
-- Name: uq_family_invites_token_hash; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_family_invites_token_hash ON public.family_invites USING btree (token_hash);


--
-- Name: uq_game_winner_bonus_partida; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_game_winner_bonus_partida ON public.game_winner_bonuses USING btree (partida_id, game_type);


--
-- Name: uq_monster_hunt_scan_reading; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_monster_hunt_scan_reading ON public.monster_hunt_scans USING btree (leitura_id) WHERE (leitura_id IS NOT NULL);


--
-- Name: uq_monster_hunt_team_state; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_monster_hunt_team_state ON public.monster_hunt_team_states USING btree (partida_id, time_id);


--
-- Name: uq_settings_empresa_key; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_settings_empresa_key ON public.settings USING btree (COALESCE(empresa_id, ''::text), setting_key);


--
-- Name: uq_zonas_equipes_scan_reading; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_zonas_equipes_scan_reading ON public.zonas_equipes_scans USING btree (leitura_id) WHERE (leitura_id IS NOT NULL);


--
-- Name: uq_zonas_equipes_team_state; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_zonas_equipes_team_state ON public.zonas_equipes_teams_states USING btree (partida_id, time_id);


--
-- Name: uq_zone_individual_scan_reading; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_zone_individual_scan_reading ON public.zone_conquest_individual_scans USING btree (leitura_id) WHERE (leitura_id IS NOT NULL);


--
-- Name: uq_zone_team_scan_reading; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_zone_team_scan_reading ON public.zone_conquest_team_scans USING btree (leitura_id) WHERE (leitura_id IS NOT NULL);


--
-- Name: checkpoint_tags FK__checkpoin__check__01142BA1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checkpoint_tags
    ADD CONSTRAINT "FK__checkpoin__check__01142BA1" FOREIGN KEY (checkpoint_id) REFERENCES public.checkpoints(id);


--
-- Name: checkpoints FK__checkpoin__event__7B5B524B; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checkpoints
    ADD CONSTRAINT "FK__checkpoin__event__7B5B524B" FOREIGN KEY (evento_id) REFERENCES public.eventos(id);


--
-- Name: checkpoints FK__checkpoin__owner_crianca; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checkpoints
    ADD CONSTRAINT "FK__checkpoin__owner_crianca" FOREIGN KEY (territory_owner_crianca_id) REFERENCES public.criancas(id);


--
-- Name: checkpoints FK__checkpoin__terri__7C4F7684; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checkpoints
    ADD CONSTRAINT "FK__checkpoin__terri__7C4F7684" FOREIGN KEY (territory_owner_time_id) REFERENCES public.times(id);


--
-- Name: crianca_conquistas FK__crianca_c__conqu__17F790F9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.crianca_conquistas
    ADD CONSTRAINT "FK__crianca_c__conqu__17F790F9" FOREIGN KEY (conquista_id) REFERENCES public.conquistas(id);


--
-- Name: crianca_conquistas FK__crianca_c__crian__17036CC0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.crianca_conquistas
    ADD CONSTRAINT "FK__crianca_c__crian__17036CC0" FOREIGN KEY (crianca_id) REFERENCES public.criancas(id);


--
-- Name: criancas FK__criancas__evento__6E01572D; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.criancas
    ADD CONSTRAINT "FK__criancas__evento__6E01572D" FOREIGN KEY (evento_id) REFERENCES public.eventos(id);


--
-- Name: criancas FK__criancas__time_i__6EF57B66; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.criancas
    ADD CONSTRAINT "FK__criancas__time_i__6EF57B66" FOREIGN KEY (time_id) REFERENCES public.times(id);


--
-- Name: evento_brincadeiras FK__evento_br__brinc__619B8048; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evento_brincadeiras
    ADD CONSTRAINT "FK__evento_br__brinc__619B8048" FOREIGN KEY (brincadeira_id) REFERENCES public.brincadeiras(id);


--
-- Name: evento_brincadeiras FK__evento_br__event__60A75C0F; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evento_brincadeiras
    ADD CONSTRAINT "FK__evento_br__event__60A75C0F" FOREIGN KEY (evento_id) REFERENCES public.eventos(id);


--
-- Name: eventos FK__eventos__cliente__5441852A; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos
    ADD CONSTRAINT "FK__eventos__cliente__5441852A" FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: leituras FK__leituras__checkp__06CD04F7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leituras
    ADD CONSTRAINT "FK__leituras__checkp__06CD04F7" FOREIGN KEY (checkpoint_id) REFERENCES public.checkpoints(id);


--
-- Name: leituras FK__leituras__crianc__07C12930; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leituras
    ADD CONSTRAINT "FK__leituras__crianc__07C12930" FOREIGN KEY (crianca_id) REFERENCES public.criancas(id);


--
-- Name: logins FK__logins__empresa___6BE40491; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.logins
    ADD CONSTRAINT "FK__logins__empresa___6BE40491" FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: logs FK__logs__cliente_id__208CD6FA; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT "FK__logs__cliente_id__208CD6FA" FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: logs FK__logs__evento_id__2180FB33; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT "FK__logs__evento_id__2180FB33" FOREIGN KEY (evento_id) REFERENCES public.eventos(id);


--
-- Name: mensagens_display FK__mensagens__event__1CBC4616; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensagens_display
    ADD CONSTRAINT "FK__mensagens__event__1CBC4616" FOREIGN KEY (evento_id) REFERENCES public.eventos(id);


--
-- Name: pontuacoes FK__pontuacoe__check__0F624AF8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pontuacoes
    ADD CONSTRAINT "FK__pontuacoe__check__0F624AF8" FOREIGN KEY (checkpoint_id) REFERENCES public.checkpoints(id);


--
-- Name: pontuacoes FK__pontuacoe__crian__0D7A0286; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pontuacoes
    ADD CONSTRAINT "FK__pontuacoe__crian__0D7A0286" FOREIGN KEY (crianca_id) REFERENCES public.criancas(id);


--
-- Name: pontuacoes FK__pontuacoe__event__0C85DE4D; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pontuacoes
    ADD CONSTRAINT "FK__pontuacoe__event__0C85DE4D" FOREIGN KEY (evento_id) REFERENCES public.eventos(id);


--
-- Name: pulseiras FK__pulseiras__crian__73BA3083; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pulseiras
    ADD CONSTRAINT "FK__pulseiras__crian__73BA3083" FOREIGN KEY (crianca_id) REFERENCES public.criancas(id);


--
-- Name: times FK__times__evento_id__66603565; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.times
    ADD CONSTRAINT "FK__times__evento_id__66603565" FOREIGN KEY (evento_id) REFERENCES public.eventos(id);


--
-- Name: zonas FK__zonas__evento_id__25518C17; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zonas
    ADD CONSTRAINT "FK__zonas__evento_id__25518C17" FOREIGN KEY (evento_id) REFERENCES public.eventos(id);


--
-- Name: brincadeiras FK_brincadeiras_empresas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.brincadeiras
    ADD CONSTRAINT "FK_brincadeiras_empresas" FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: checkpoints FK_checkpoints_empresas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checkpoints
    ADD CONSTRAINT "FK_checkpoints_empresas" FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: criancas FK_criancas_empresas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.criancas
    ADD CONSTRAINT "FK_criancas_empresas" FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: eventos FK_eventos_empresas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos
    ADD CONSTRAINT "FK_eventos_empresas" FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: leituras FK_leituras_empresas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leituras
    ADD CONSTRAINT "FK_leituras_empresas" FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: pontuacoes FK_pontuacoes_empresas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pontuacoes
    ADD CONSTRAINT "FK_pontuacoes_empresas" FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: pulseiras FK_pulseiras_empresas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pulseiras
    ADD CONSTRAINT "FK_pulseiras_empresas" FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: times FK_times_empresas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.times
    ADD CONSTRAINT "FK_times_empresas" FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: family_linking_codes family_linking_codes_crianca_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.family_linking_codes
    ADD CONSTRAINT family_linking_codes_crianca_id_fkey FOREIGN KEY (crianca_id) REFERENCES public.criancas(id);


--
-- Name: family_linking_codes family_linking_codes_empresa_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.family_linking_codes
    ADD CONSTRAINT family_linking_codes_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: family_linking_codes family_linking_codes_evento_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.family_linking_codes
    ADD CONSTRAINT family_linking_codes_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES public.eventos(id);


--
-- Name: family_linking_codes family_linking_codes_used_by_login_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.family_linking_codes
    ADD CONSTRAINT family_linking_codes_used_by_login_id_fkey FOREIGN KEY (used_by_login_id) REFERENCES public.logins(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: TABLE brincadeiras; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.brincadeiras TO anon;
GRANT ALL ON TABLE public.brincadeiras TO authenticated;
GRANT ALL ON TABLE public.brincadeiras TO service_role;


--
-- Name: TABLE caca_tesouro_partidas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.caca_tesouro_partidas TO anon;
GRANT ALL ON TABLE public.caca_tesouro_partidas TO authenticated;
GRANT ALL ON TABLE public.caca_tesouro_partidas TO service_role;


--
-- Name: TABLE caca_tesouro_scans; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.caca_tesouro_scans TO anon;
GRANT ALL ON TABLE public.caca_tesouro_scans TO authenticated;
GRANT ALL ON TABLE public.caca_tesouro_scans TO service_role;


--
-- Name: TABLE caca_tesouro_tempos; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.caca_tesouro_tempos TO anon;
GRANT ALL ON TABLE public.caca_tesouro_tempos TO authenticated;
GRANT ALL ON TABLE public.caca_tesouro_tempos TO service_role;


--
-- Name: TABLE checkpoint_tags; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.checkpoint_tags TO anon;
GRANT ALL ON TABLE public.checkpoint_tags TO authenticated;
GRANT ALL ON TABLE public.checkpoint_tags TO service_role;


--
-- Name: SEQUENCE checkpoint_tags_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.checkpoint_tags_id_seq TO anon;
GRANT ALL ON SEQUENCE public.checkpoint_tags_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.checkpoint_tags_id_seq TO service_role;


--
-- Name: TABLE checkpoints; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.checkpoints TO anon;
GRANT ALL ON TABLE public.checkpoints TO authenticated;
GRANT ALL ON TABLE public.checkpoints TO service_role;


--
-- Name: TABLE clientes; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.clientes TO anon;
GRANT ALL ON TABLE public.clientes TO authenticated;
GRANT ALL ON TABLE public.clientes TO service_role;


--
-- Name: TABLE conquistas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.conquistas TO anon;
GRANT ALL ON TABLE public.conquistas TO authenticated;
GRANT ALL ON TABLE public.conquistas TO service_role;


--
-- Name: TABLE crianca_conquistas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.crianca_conquistas TO anon;
GRANT ALL ON TABLE public.crianca_conquistas TO authenticated;
GRANT ALL ON TABLE public.crianca_conquistas TO service_role;


--
-- Name: TABLE criancas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.criancas TO anon;
GRANT ALL ON TABLE public.criancas TO authenticated;
GRANT ALL ON TABLE public.criancas TO service_role;


--
-- Name: TABLE empresa_event_control; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.empresa_event_control TO anon;
GRANT ALL ON TABLE public.empresa_event_control TO authenticated;
GRANT ALL ON TABLE public.empresa_event_control TO service_role;


--
-- Name: TABLE empresas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.empresas TO anon;
GRANT ALL ON TABLE public.empresas TO authenticated;
GRANT ALL ON TABLE public.empresas TO service_role;


--
-- Name: TABLE event_game_state; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.event_game_state TO anon;
GRANT ALL ON TABLE public.event_game_state TO authenticated;
GRANT ALL ON TABLE public.event_game_state TO service_role;


--
-- Name: TABLE evento_brincadeiras; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.evento_brincadeiras TO anon;
GRANT ALL ON TABLE public.evento_brincadeiras TO authenticated;
GRANT ALL ON TABLE public.evento_brincadeiras TO service_role;


--
-- Name: TABLE eventos; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.eventos TO anon;
GRANT ALL ON TABLE public.eventos TO authenticated;
GRANT ALL ON TABLE public.eventos TO service_role;


--
-- Name: TABLE family_child_links; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.family_child_links TO anon;
GRANT ALL ON TABLE public.family_child_links TO authenticated;
GRANT ALL ON TABLE public.family_child_links TO service_role;


--
-- Name: TABLE family_invites; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.family_invites TO anon;
GRANT ALL ON TABLE public.family_invites TO authenticated;
GRANT ALL ON TABLE public.family_invites TO service_role;


--
-- Name: TABLE family_linking_codes; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.family_linking_codes TO anon;
GRANT ALL ON TABLE public.family_linking_codes TO authenticated;
GRANT ALL ON TABLE public.family_linking_codes TO service_role;


--
-- Name: TABLE game_sessions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.game_sessions TO anon;
GRANT ALL ON TABLE public.game_sessions TO authenticated;
GRANT ALL ON TABLE public.game_sessions TO service_role;


--
-- Name: TABLE game_winner_bonuses; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.game_winner_bonuses TO anon;
GRANT ALL ON TABLE public.game_winner_bonuses TO authenticated;
GRANT ALL ON TABLE public.game_winner_bonuses TO service_role;


--
-- Name: TABLE leituras; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.leituras TO anon;
GRANT ALL ON TABLE public.leituras TO authenticated;
GRANT ALL ON TABLE public.leituras TO service_role;


--
-- Name: TABLE logins; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.logins TO anon;
GRANT ALL ON TABLE public.logins TO authenticated;
GRANT ALL ON TABLE public.logins TO service_role;


--
-- Name: TABLE logs; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.logs TO anon;
GRANT ALL ON TABLE public.logs TO authenticated;
GRANT ALL ON TABLE public.logs TO service_role;


--
-- Name: SEQUENCE logs_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.logs_id_seq TO anon;
GRANT ALL ON SEQUENCE public.logs_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.logs_id_seq TO service_role;


--
-- Name: TABLE mensagens_display; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.mensagens_display TO anon;
GRANT ALL ON TABLE public.mensagens_display TO authenticated;
GRANT ALL ON TABLE public.mensagens_display TO service_role;


--
-- Name: TABLE monster_hunt_partidas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.monster_hunt_partidas TO anon;
GRANT ALL ON TABLE public.monster_hunt_partidas TO authenticated;
GRANT ALL ON TABLE public.monster_hunt_partidas TO service_role;


--
-- Name: TABLE monster_hunt_scans; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.monster_hunt_scans TO anon;
GRANT ALL ON TABLE public.monster_hunt_scans TO authenticated;
GRANT ALL ON TABLE public.monster_hunt_scans TO service_role;


--
-- Name: TABLE monster_hunt_team_states; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.monster_hunt_team_states TO anon;
GRANT ALL ON TABLE public.monster_hunt_team_states TO authenticated;
GRANT ALL ON TABLE public.monster_hunt_team_states TO service_role;


--
-- Name: TABLE pontuacoes; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.pontuacoes TO anon;
GRANT ALL ON TABLE public.pontuacoes TO authenticated;
GRANT ALL ON TABLE public.pontuacoes TO service_role;


--
-- Name: TABLE pulseiras; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.pulseiras TO anon;
GRANT ALL ON TABLE public.pulseiras TO authenticated;
GRANT ALL ON TABLE public.pulseiras TO service_role;


--
-- Name: TABLE settings; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.settings TO anon;
GRANT ALL ON TABLE public.settings TO authenticated;
GRANT ALL ON TABLE public.settings TO service_role;


--
-- Name: SEQUENCE settings_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.settings_id_seq TO anon;
GRANT ALL ON SEQUENCE public.settings_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.settings_id_seq TO service_role;


--
-- Name: TABLE staff; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.staff TO anon;
GRANT ALL ON TABLE public.staff TO authenticated;
GRANT ALL ON TABLE public.staff TO service_role;


--
-- Name: TABLE support_tickets; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.support_tickets TO anon;
GRANT ALL ON TABLE public.support_tickets TO authenticated;
GRANT ALL ON TABLE public.support_tickets TO service_role;


--
-- Name: TABLE times; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.times TO anon;
GRANT ALL ON TABLE public.times TO authenticated;
GRANT ALL ON TABLE public.times TO service_role;


--
-- Name: TABLE zonas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zonas TO anon;
GRANT ALL ON TABLE public.zonas TO authenticated;
GRANT ALL ON TABLE public.zonas TO service_role;


--
-- Name: TABLE zonas_equipes_partidas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zonas_equipes_partidas TO anon;
GRANT ALL ON TABLE public.zonas_equipes_partidas TO authenticated;
GRANT ALL ON TABLE public.zonas_equipes_partidas TO service_role;


--
-- Name: TABLE zonas_equipes_scans; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zonas_equipes_scans TO anon;
GRANT ALL ON TABLE public.zonas_equipes_scans TO authenticated;
GRANT ALL ON TABLE public.zonas_equipes_scans TO service_role;


--
-- Name: TABLE zonas_equipes_teams_states; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zonas_equipes_teams_states TO anon;
GRANT ALL ON TABLE public.zonas_equipes_teams_states TO authenticated;
GRANT ALL ON TABLE public.zonas_equipes_teams_states TO service_role;


--
-- Name: TABLE zone_conquest_checkpoint_states; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zone_conquest_checkpoint_states TO anon;
GRANT ALL ON TABLE public.zone_conquest_checkpoint_states TO authenticated;
GRANT ALL ON TABLE public.zone_conquest_checkpoint_states TO service_role;


--
-- Name: TABLE zone_conquest_individual_checkpoint_protection; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zone_conquest_individual_checkpoint_protection TO anon;
GRANT ALL ON TABLE public.zone_conquest_individual_checkpoint_protection TO authenticated;
GRANT ALL ON TABLE public.zone_conquest_individual_checkpoint_protection TO service_role;


--
-- Name: TABLE zone_conquest_individual_participant_states; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zone_conquest_individual_participant_states TO anon;
GRANT ALL ON TABLE public.zone_conquest_individual_participant_states TO authenticated;
GRANT ALL ON TABLE public.zone_conquest_individual_participant_states TO service_role;


--
-- Name: TABLE zone_conquest_individual_partidas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zone_conquest_individual_partidas TO anon;
GRANT ALL ON TABLE public.zone_conquest_individual_partidas TO authenticated;
GRANT ALL ON TABLE public.zone_conquest_individual_partidas TO service_role;


--
-- Name: TABLE zone_conquest_individual_scans; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zone_conquest_individual_scans TO anon;
GRANT ALL ON TABLE public.zone_conquest_individual_scans TO authenticated;
GRANT ALL ON TABLE public.zone_conquest_individual_scans TO service_role;


--
-- Name: TABLE zone_conquest_team_partidas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zone_conquest_team_partidas TO anon;
GRANT ALL ON TABLE public.zone_conquest_team_partidas TO authenticated;
GRANT ALL ON TABLE public.zone_conquest_team_partidas TO service_role;


--
-- Name: TABLE zone_conquest_team_scans; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zone_conquest_team_scans TO anon;
GRANT ALL ON TABLE public.zone_conquest_team_scans TO authenticated;
GRANT ALL ON TABLE public.zone_conquest_team_scans TO service_role;


--
-- Name: TABLE zone_conquest_team_tempos; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zone_conquest_team_tempos TO anon;
GRANT ALL ON TABLE public.zone_conquest_team_tempos TO authenticated;
GRANT ALL ON TABLE public.zone_conquest_team_tempos TO service_role;


--
-- Name: TABLE zone_conquest_zone_states; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.zone_conquest_zone_states TO anon;
GRANT ALL ON TABLE public.zone_conquest_zone_states TO authenticated;
GRANT ALL ON TABLE public.zone_conquest_zone_states TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

